# Generated by Django 5.2.1 on 2025-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
