# Generated by Django 5.2 on 2025-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
