# Generated by Django 5.2 on 2025-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_play_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_upload',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
