# Generated by Django 5.2 on 2025-04-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_play_count'),
        ('songs', '0005_alter_song_mv'),
    ]

    operations = [
    ]
